### ISSUE TITLE
前端似乎又改了

### ISSUE THREAD

**Issue by poloniumn** [tankeryang/banciyuan-downloader#1]
不能用了，我不会写python，但是看了一下代码发现代码里面获取作品数目的地方和半次元现在的似乎不匹配，尝试修改以后并没有成功，还望有时间能够修复一下，谢了~

**Comment by tankeryang** [comment]
ok，我看到了，这两天看看

**Comment by tankeryang** [comment]
@poloniumn 已经修复了，更新了版本，功能更强了点
