### ISSUE TITLE
您好，好像登录的方式又变了。

### ISSUE THREAD

**Issue by shakingk** [tankeryang/banciyuan-downloader#2]
看了一下请求和您的代码，发现好像好像dologin的请求参数改变了。刚学爬虫不久，所以不是很清楚。第一次提issue，格式上和方法有不对的地方请见谅。

**Comment by tankeryang** [comment]
@shakingk 这么夸张？又改了？这两天看看。

**Comment by tankeryang** [comment]
@shakingk 刚刚修复了，测试了一下没问题，就是登录的时候多请求了一层url，然后表单参数有点变化。你看看代码就知道了
