### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by wengermyy** [tankeryang/banciyuan-downloader#4]
您好，我是头一次用python爬虫，好不容易把环境搞定了，下载下来几个coser的文件夹都显示粉丝可见，问题是这几个coser的作品并非粉丝可见，请问是有BUG还是哪一步操作错了？

**Comment by tankeryang** [comment]
好的，过两天周末看看。估计是前端页面的问题

**Comment by tankeryang** [comment]
@wengermyy 能不能给一下coser的id呢？

**Comment by wengermyy** [comment]
windows 8.1; python 3.7.1; beautifulsoup 4.7.0; requests 2.21.0; lxml 4.2.6

**Comment by wengermyy** [comment]
<img src="https://i.loli.net/2019/01/03/5c2e17a2752d2.png">

**Comment by wengermyy** [comment]
https://i.loli.net/2019/01/03/5c2e17a2752d2.png
